var pagewidth;var GSAfire;var canShowGSASuggest=false;$anujq(document).ready(function(){$anujq("#explore-li-1").hoverIntent(function(){slideDownID(".explore-hdr-jqshow")},function(){fadeOutID(".explore-hdr-jqshow")});$anujq("#explore-li-2").hoverIntent(function(){slideDownID(".explore-hdr-az-jqshow")},function(){fadeOutID(".explore-hdr-az-jqshow")});$anujq("#srch-hdr-mini").hoverIntent(function(){slideDownID(".explore-hdr-searchmini-jqshow")},function(){fadeOutID(".explore-hdr-searchmini-jqshow")});$anujq("#ac-areas-li").hoverIntent(function(){fadeInIDandAddBox(".ac-areas-jqshow","#ac-areas-li")},function(){fadeOutIDandRemoveBox(".ac-areas-jqshow","#ac-areas-li")});$anujq("#ac-gov-li").hoverIntent(function(){fadeInIDandAddBox(".ac-gov-jqshow","#ac-gov-li")},function(){fadeOutIDandRemoveBox(".ac-gov-jqshow","#ac-gov-li")});$anujq("#ac-prog-li").hoverIntent(function(){fadeInIDandAddBox(".ac-prog-jqshow","#ac-prog-li")},function(){fadeOutIDandRemoveBox(".ac-prog-jqshow","#ac-prog-li")});if(getCookie('ignore-ie7')){$anujq("#ie7-warn").hide();}
$anujq(".anu-share").show();if(!$anujq("html").hasClass("ie6")&&!$anujq("html").hasClass("ie7")&&!$anujq("html").hasClass("ie8")&&!$anujq("html").hasClass("ie9")){setupGSAauto();}
setupSocials();setupEnquireButtons();setupFeedbackButtons();checkSkipnav();setupFormReq();pagewidth=$anujq('body').width();if($anujq("html").hasClass("ie7")){$anujq('<img src="../anu/images/icons/external.png" style="padding-left:3px;border:none;" />').appendTo(".link-ext");$anujq('<img src="../anu/images/icons/new-window.png" style="padding-left:3px;border:none;" />').appendTo(".link-new-win");}
if(!$anujq("html").hasClass("ie6")&&!$anujq("html").hasClass("ie7")&&!$anujq("html").hasClass("ie8")&&!$anujq("html").hasClass("ie9")){$anujq(window).resize(function(){newpagewidth=$anujq('body').width();if(pagewidth<960&&newpagewidth>=960){changeUpTo960();}else if(pagewidth>=960&&newpagewidth<960){changeDownTo600();}
pagewidth=newpagewidth;});}
$anujq('[name="stype"]').change(function(){changeSearch('stype');});$anujq('[name=stype-2]').change(function(){changeSearch('stype-2');});$anujq('[name=stype-3]').change(function(){changeSearch('stype-3');});myCookie=getCookie('anuMobile');if(myCookie){showID('#menu');}
imageObj=new Image();imageObj.src="../anu/images/logos/2x_anu_logo_over.png";});function setupGSAauto(){$anujq(".srch-gw2 .globalsearch, .srch-gw2 .searchminidrop #qt1, .bnr-gw2-search #qt, #gw-mobile-menu-wrap #gw-menuslidecover").after("<div class='gsasuggest'></div>");$anujq(' #bnr-wrap #qt, #bnr-wrap .gsasuggest, #bnr-wrap, #body-wrap, #update-wrap, #footer-wrap, #gw-mobile-menu-nav, #gw-mobile-menu-wrap .mobile-menu-toggle, #gw-mobile-menu-wrap .mobile-search-toggle').click(function(event){if($anujq(this).attr('id')=='qt'||$anujq(this).hasClass('gsasuggest')){event.stopPropagation();return;}
$anujq(".gsasuggest").hide();canShowGSASuggest=false;});$anujq('.srch-gw2 #qt, .srch-gw2 .searchminidrop #qt1, .bnr-gw2-search #qt, .bnr-gw2-search #qt1').click(function(){if(!$anujq(this).val()){$anujq(".gsasuggest").hide();canShowGSASuggest=false;}});$anujq('.srch-gw2 #qt, .srch-gw2 .searchminidrop #qt1, .bnr-gw2-search #qt, .bnr-gw2-search #qt1').keyup(function(){if(GSAfire){clearTimeout(GSAfire);}
if($anujq(this).val()){x=$anujq(this).val();GSAfire=setTimeout(function(){fireGSAsuggest(x)},200);canShowGSASuggest=true;}else{$anujq(".gsasuggest").hide();canShowGSASuggest=false;}});$anujq('.srch-gw2 #qt, .srch-gw2 .searchminidrop #qt1, .bnr-gw2-search #qt, .bnr-gw2-search #qt1').focus(function(){if($anujq(this).val()){$anujq(".gsasuggest").show();canShowGSASuggest=true;}});}
function fireGSAsuggest(query){request=$anujq.ajax({url:"http://find.anu.edu.au/suggest",crossDomain:true,dataType:"jsonp",jsonpCallback:"loaded_gsa_sug",data:{max:"10",site:"public_collection",client:"anu_frontend",format:"os",q:query}});}
function loaded_gsa_sug(data){$anujq(".gsasuggest").html('');if(data[1].length==0){$anujq(".gsasuggest").hide();return;}
if(canShowGSASuggest){$anujq(".gsasuggest").show();}
var newul=document.createElement("ul");for(i=0;i<data[1].length;i++){data[1][i]=data[1][i].replace(/\\x22/g,'&#34;');data[1][i]=data[1][i].replace(/\\x27/g,'&#39;');data[1][i]=data[1][i].replace(/\\x26/g,'&#38;');data[1][i]=data[1][i].replace(/\\x3c/g,'&#60;');data[1][i]=data[1][i].replace(/\\x3e/g,'&#62;');$anujq(newul).append("<li><a href='http://find.anu.edu.au/search?client=anu_frontend&proxystylesheet=anu_frontend&site=default_collection&btnG=Search&filter=0&q="+data[1][i]+"'><strong>"+data[1][i].substr(0,data[0].length)+"</strong>"+data[1][i].substr(data[0].length)+"</a></li>");}
$anujq(".gsasuggest").append(newul);}
function setupEnquireButtons(){enqA=["uni","cass","cap","cbe","cecs","col","cmbe","cpms","nsc"];for(i=0;i<enqA.length;i++){$anujq('.anu-enq-'+enqA[i]).html("<a href='http://www.anu.edu.au/contact/'><img src='../anu/images/enquire/anu-enq-"+enqA[i]+".png' onmouseover=\"this.src='../anu/images/enquire/anu-enq-"+enqA[i]+"-over.png'\" onmouseout=\"this.src='../anu/images/enquire/anu-enq-"+enqA[i]+".png'\" alt='Enquire now'></a>");$anujq('.anu-enq-'+enqA[i]+':first').each(function(){imageObj=new Image();imageObj.src="../anu/images/enquire/anu-enq-"+enqA[i]+"-over.png";});}}
function setupFeedbackButtons(){fbA=["uni"];for(i=0;i<fbA.length;i++){$anujq('.anu-feedback-'+fbA[i]).html("<a href='http://students.anu.edu.au/feedback/'><img src='../anu/images/feedback/anu-feedback-"+fbA[i]+".png' onmouseover=\"this.src='../anu/images/feedback/anu-feedback-"+fbA[i]+"-over.png'\" onmouseout=\"this.src='../anu/images/feedback/anu-feedback-"+fbA[i]+".png'\" alt='Student feedback'></a>");$anujq('.anu-feedback-'+fbA[i]+':first').each(function(){imageObj=new Image();imageObj.src="../anu/images/feedback/anu-feedback-"+fbA[i]+"-over.png";});}}
function setupFormReq(){$anujq('.anuform label.req').each(function(){idfor=$anujq(this).attr('for');$anujq('#'+idfor).attr('aria-required','true');$anujq('#'+idfor).prop('required',true);$anujq(this).append("<img src='../anu/images/styles/asterisk.png' alt=' required'>");$anujq(this).removeClass('req');});}
function setupSocials(){$anujq('.anu-share').each(function(){sharetext="<ul><li><a href='#' onclick=\"location.href='mailto:?subject='+encodeURIComponent(document.title)+'&body='+encodeURIComponent(document.title)+' : '+encodeURIComponent(location.href);\"><img class='absmiddle' src='../anu/images/share/email.png' alt='Email this page'></a></li><li><a href='http://www.facebook.com/sharer.php' onclick=\"window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(location.href)+'&t='+encodeURIComponent(document.title), 'Facebook','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/facebook.png' alt='Post on Facebook'></a></li><li><a href='http://twitter.com/home' onclick=\"window.open('http://twitter.com/home/?status='+encodeURIComponent('#ANU Currently reading '+document.title)+' at '+encodeURIComponent(location.href), 'twitter','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/twitter.png' alt='Tweet'></a></li>";if($anujq(this).attr('data-anu-pinterest')){getpin=$anujq(this).attr('data-anu-pinterest');sharetext+="<li><a href='http://www.pinterest.com/pin/create/button/' onclick=\"window.open('http://www.pinterest.com/pin/create/button/?url='+encodeURIComponent(location.href)+'&media='+encodeURIComponent(getpin)+'&description='+encodeURIComponent(document.title), 'pinterest','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/pinterest.png' alt='Pinterest'></a></li>";}
if($anujq("html").hasClass("ie6")||$anujq("html").hasClass("ie7")||$anujq("html").hasClass("ie8")){sharetext+="<li class='anu-share-more'><a  href='#' onclick=\"return false;\"><img class='absmiddle' src='../anu/images/share/share.png' alt='Share...'></a><ul class='anu-share-icons'><li id='anu-share-close'><a href='#' onclick=\"fadeOutID($anujq('.anu-share-icons')); return false;\" >close <img  alt='' src='../anu/images/buttons/btn-close.gif'></a></li>";}else{sharetext+="<li class='anu-share-more'><a  href='#' onclick=\"slideDownID($anujq(this).parent().find('.anu-share-icons')); return false;\"  ><img class='absmiddle' src='../anu/images/share/share.png' alt='Share...'></a><ul class='anu-share-icons'><li id='anu-share-close'><a href='#' onclick=\"fadeOutID($anujq(this).parent().parent()); return false;\" >close <img  alt='' src='../anu/images/buttons/btn-close.gif'></a></li>";}
sharetext+="<li><a href='http://delicious.com/save' onclick=\"window.open('http://delicious.com/save?v=5&noui&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'delicious','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/delicious.png' alt='Delicious' title='Delicious'/></a></li><li><a href=\"http://digg.com/submit\" onclick=\"window.open('http://digg.com/submit?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'digg','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/digg.png' alt='Digg' title='Digg'/></a></li><li><a href='https://plus.google.com/share' onclick=\"window.open('https://plus.google.com/share?url='+encodeURIComponent(location.href), 'gplusshare', 'toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/google-plus.png' alt='Google+' title='Google+'/></a></li><li><a href='http://www.linkedin.com/shareArticle' onclick=\"window.open('http://www.linkedin.com/shareArticle?mini=true&url='+encodeURIComponent(location.href), 'Linked In','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/linkedin.png' alt='Linked In' title='LinkedIn'/></a></li><li><a href='http://reddit.com/submit' onclick=\"window.open('http://reddit.com/submit?url='+encodeURIComponent(location.href), 'Reddit','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/reddit.png' alt='Reddit' title='Reddit'/></a></li><li><a href='http://www.stumbleupon.com/submit' onclick=\"window.open('http://www.stumbleupon.com/submit?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'StumbleUpon','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/stumbleupon.png' alt='Stumbleupon' title='StumbleUpon'/></a></li><li><a href='http://www.tumblr.com' onclick=\"window.open('http://www.tumblr.com/share/link?url='+encodeURIComponent(location.href), 'Tumblr','toolbar=no,width=550,height=550, left='+(screen.availWidth/2-275)+',top='+(screen.availHeight/2-225)+''); return false;\"><img class='absmiddle' src='../anu/images/share/tumblr.png' alt='Tumblr' title='Tumblr'/></a></li></ul></li></ul>";$anujq(this).html(sharetext);});$anujq(".anu-share-more").hoverIntent(function(){slideDownID($anujq(this).find(".anu-share-icons"))},function(){fadeOutID($anujq(this).find(".anu-share-icons"))});}
function changeDownTo600(){myCookie=getCookie('anuMobile');if(!(myCookie)){hideID('#menu');}}
function changeUpTo960(){showID('#menu');}
function slideDownIDandHideFeatures(id){$anujq('#anu-features-rotating').hide();$anujq(id).stop(true,true).slideDown('fast');}
function fadeOutIDandShowFeatures(id){$anujq(id).stop(true,true).fadeOut('fast');$anujq('#anu-features-rotating').show();}
function fadeInIDandAddBox(id,id2){$anujq(id).stop(true,true).fadeIn('fast');$anujq(id2).css('border-right','2px solid #94b0be');$anujq(id2).css('background-color','#94b0be');$anujq(id2+" a:first").css('color','#ffffff');}
function slideDownIDandAddBox(id,id2){$anujq(id).stop(true,true).slideDown('fast');$anujq(id2).css('border-right','2px solid #94b0be');$anujq(id2).css('background-color','#94b0be');$anujq(id2+" a:first").css('color','#ffffff');}
function fadeOutIDandRemoveBox(id,id2){$anujq(id).stop(true,true).fadeOut('fast');$anujq(id2).css('border-right','none');$anujq(id2).css('background-color','transparent');$anujq(id2+" a:first").css('color','#527688');}
function slideDownID(id){$anujq(id).stop(true,true).slideDown('fast');}
function fadeInID(id){$anujq(id).stop(true,true).fadeIn('fast');}
function fadeOutID(id){$anujq(id).stop(true,true).fadeOut('fast');}
function showID(id){$anujq(id).show();}
function hideID(id){$anujq(id).hide();}
function slideDownFadeOutToggle(id){if($anujq(id).is(':visible')){if(id=="#menu"){deleteCookie('anuMobile','/',null);}
hideID(id);}else{if(id=="#menu"){setCookie('anuMobile','1',expdate,'/',null);}
slideDownID(id);}}
function showhide(id){if(document.getElementById){obj=document.getElementById(id);if(obj!=null){if(obj.style.display=="none"){obj.style.display="";}else{obj.style.display="none";}
return true;}}
return false;}
function clearInput(theinput){if(theinput.value==theinput.defaultValue){theinput.value='';$anujq(theinput).removeClass('textinactive');}}
function defaultInput(theinput){if(theinput.value==''){theinput.value=theinput.defaultValue;$anujq(theinput).addClass('textinactive');}}
function checkSkipnav(){var is_webkit=navigator.userAgent.toLowerCase().indexOf('webkit')>-1;var is_opera=navigator.userAgent.toLowerCase().indexOf('opera')>-1;if(is_webkit||is_opera){if(document.getElementById('content')!=null){var link=document.createElement('a');link.setAttribute('href','#content');link.setAttribute('class','skipnavtarget');link.setAttribute('id','skipnavlink');if(document.getElementById("content").firstChild!=null){document.getElementById("content").insertBefore(link,document.getElementById("content").firstChild);}else{document.getElementById("content").appendChild(link);}
target=document.getElementById("skipnav");if(target!=null){target.href="#content";target.setAttribute("tabindex","0");target.setAttribute("onclick","document.getElementById('skipnavlink').focus();");}}}}
function checkSearch(){myCookie=getCookie('anuSearch');if(myCookie){setCheckedValue('stype',myCookie);setSelectedValue('stype-2',myCookie);setSelectedValue('stype-3',myCookie);}}
function changeSearch(fromsrc){if(fromsrc=="stype-2"){$anujq("#stype-3").val($anujq("#"+fromsrc).val());$anujq('input:radio[name="stype"][value="'+$anujq("#"+fromsrc).val()+'"]').prop('checked',true);}
if(fromsrc=="stype-3"){$anujq("#stype-2").val($anujq("#"+fromsrc).val());$anujq('input:radio[name="stype"][value="'+$anujq("#"+fromsrc).val()+'"]').prop('checked',true);}
if(fromsrc=="stype"){$anujq("#stype-2").val($anujq('input:radio[name="stype"]:checked').val());$anujq("#stype-3").val($anujq('input:radio[name="stype"]:checked').val());}}
function checkInput(theinput,themessage){elem=document.getElementById(theinput);if(elem){oldelem=elem.value;elem.value=elem.value.replace(/^\s+|\s+$/g,'');if(elem.value==""||elem.value==elem.defaultValue){clearInput(elem);alert(themessage);elem.focus()
return false;}
elem.value=oldelem;setCookie('anuSearch',getCheckedValue('stype'),expdate,'/',null);}}
function getSelectedValue(selectObj){return $anujq('[name='+selectObj+']').val();}
function getCheckedValue(radioObj){return $anujq('input[name='+radioObj+']:checked').val();}
function setSelectedValue(selectObj,newValue){$anujq('[name='+selectObj+']').val(newValue);}
function setCheckedValue(radioObj,newValue){$anujq('input[name='+radioObj+']').each(function(){if($anujq(this).val()==newValue.toString()){$anujq(this).attr('checked',true);}else{$anujq(this).attr('checked',false);}});}
function getCookieVal(offset){var endstr=document.cookie.indexOf(";",offset);if(endstr==-1){endstr=document.cookie.length;}
return unescape(document.cookie.substring(offset,endstr));}
function setCookie(name,value,expires,path,domain,secure){document.cookie=name+"="+escape(value)+
((expires)?"; expires="+expires.toGMTString():"")+
((path)?"; path="+path:"")+"; domain=.anu.edu.au"+
((secure)?"; secure":"");}
function getCookie(name){var arg=name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;while(i<clen){var j=i+alen;if(document.cookie.substring(i,j)==arg){return getCookieVal(j);}
i=document.cookie.indexOf(" ",i)+1;if(i==0){break;}}
return null;}
function deleteCookie(name,path,domain){if(getCookie(name)){document.cookie=name+"="+
((path)?"; path="+path:"")+"; domain=.anu.edu.au"+"; expires=Thu, 01-Jan-70 00:00:01 GMT";}}
function anuViewSite(no_mobile){if(no_mobile==1){deleteCookie('anuNoMobile','/',null);}else{setCookie('anuNoMobile','1',expdate,'/',null);}}
var expdate=new Date();expdate.setTime(expdate.getTime()+(1000*60*60*24*30));
/*! A fix for the iOS orientationchange zoom bug.
Script by @scottjehl, rebound by @wilto.
MIT / GPLv2 License.
*/
(function(w){var ua=navigator.userAgent;if(!(/iPhone|iPad|iPod/.test(navigator.platform)&&/OS [1-5]_[0-9_]* like Mac OS X/i.test(ua)&&ua.indexOf("AppleWebKit")>-1)){return;}
var doc=w.document;if(!doc.querySelector){return;}
var meta=doc.querySelector("meta[name=viewport]"),initialContent=meta&&meta.getAttribute("content"),disabledZoom=initialContent+",maximum-scale=1",enabledZoom=initialContent+",maximum-scale=10",enabled=true,x,y,z,aig;if(!meta){return;}
function restoreZoom(){meta.setAttribute("content",enabledZoom);enabled=true;}
function disableZoom(){meta.setAttribute("content",disabledZoom);enabled=false;}
function checkTilt(e){aig=e.accelerationIncludingGravity;x=Math.abs(aig.x);y=Math.abs(aig.y);z=Math.abs(aig.z);if((!w.orientation||w.orientation===180)&&(x>7||((z>6&&y<8||z<8&&y>6)&&x>5))){if(enabled){disableZoom();}}
else if(!enabled){restoreZoom();}}
w.addEventListener("orientationchange",restoreZoom,false);w.addEventListener("devicemotion",checkTilt,false);})(this);